### ISSUE TITLE
Add text "calling" support, to call other servers

### ISSUE THREAD

**Issue by neeleshpoli** [neeleshpoli/disc-bot#1]
Users should be able to run `/call` on the server. They will be placed in a queue. When another server has been found, let the user know that they are connected to another server. Whatever messages the users send in the channel the command was run from will be sent to the channel the other user called them from.
## How it should work
- [ ] Match servers together based on preset interests (interest-based matching) (held up, check below)
- [x] Users cannot call each other from the same server
- [x] Messages should be sent with webhooks

### Reply here for any other feature that should be implemented

**Comment by Zzaff** [comment]
Make sure the interest-based matchmaking is specified to end search after so long, to keep the bot running faster and keep it from using memory, also keeps the user from waiting as long in one interest.

**Comment by neeleshpoli** [comment]
Alright. Users cannot call each other from the same server now, it will be pushed later.

**Comment by neeleshpoli** [comment]
User now knows when the call is ended as well. They will know when the call is started. The issue of "Added to queue" message being shown after the user in sent to a call is known and a fix is being worked on.

**Comment by neeleshpoli** [comment]
The issue of "Added to queue" message being shown after the user joins a call is now fixed. Webhook support has been added.

Interest based calling will be added later, due to how users would enter their interests but it would be difficult to match them. For example, if user1 has the interests of computers and user2 has the interests of desktops, it would be difficult to identify that they are the same thing and can be paired together. The issue will be left open for people with ideas for an ideal solution. The core part of the feature is complete, so it will be marked as held up. Interest based matching might need to be a separate feature entirely.
